sudo: required

language: sh

before_install:
    - sudo apt-get update -q
    - export scversion="stable" # or "v0.4.7", or "latest"
    - wget "https://storage.googleapis.com/shellcheck/shellcheck-${scversion}.linux.x86_64.tar.xz"
    - tar --xz -xvf shellcheck-"${scversion}".linux.x86_64.tar.xz
    - sudo cp shellcheck-"${scversion}"/shellcheck /usr/bin/
    - /usr/bin/shellcheck --version
    - sudo apt install p7zip-full
    - wget http://sec.cuc.edu.cn/huangwei/course/LinuxSysAdmin/exp/chap0x04/web_log.tsv.7z
    - 7z x -oexp04 web_log.tsv.7z  

script:
  - bash test.sh

  - bash exp04/web_log.sh  
  
  - bash exp04/world_cup.sh

  
  
  - bash exp04/image_process/image.sh -i exp04/image_process/test1.jpg -o result1.jpg -q 60 
  - bash exp04/image_process/image.sh -i exp04/image_process/test2.png -o result2.jpg -r 70  
  
  - bash exp04/image_process/image.sh -i exp04/image_process/test1.jpg -o result3.jpg -w LALALALALAL
  - bash exp04/image_process/image.sh -i input -o output -p PREFIX
  - bash exp04/image_process/image.sh -i input -o output -s POSTFIX
  
  

after_script:
  - /usr/bin/shellcheck test.sh

after_failure:
  - id
  - pwd
  - df -h
  - cat error.log

notifications:
  email:
    on_success: never
